repos:
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        args: [--diff, --recursive, --parallel, --exclude=third_party]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [--config=./pyproject.toml]
      - id: ruff
        name: ruff-isort-fix
        args: [--select, I, --fix]