version: "3"

services:
  task-runner:
      build:
        context: .
        dockerfile: task-runner/Dockerfile.lite
      environment:
        EXECUTER_IMAGES_DIR: /executer-images
        API_URL: ${INDUCTIVA_API_URL}
        USER_API_KEY: ${INDUCTIVA_API_KEY}
        MACHINE_GROUP_NAME: ${MACHINE_GROUP_NAME}
      volumes:
        - ./apptainer:/executer-images
      privileged: true
      platform: linux/amd64