services:
  task-runner:
      build:
        context: .
        dockerfile: task-runner/Dockerfile
      environment:
        EXECUTER_IMAGES_DIR: /executer-images
        API_URL: ${INDUCTIVA_API_URL}
        USER_API_KEY: ${INDUCTIVA_API_KEY}
        MACHINE_GROUP_NAME: ${MACHINE_GROUP_NAME}
        HOST_NAME: ${TASK_RUNNER_HOSTNAME:-${HOSTNAME}}
      volumes:
        - ./apptainer:/executer-images
      extra_hosts:
        - "host.docker.internal:host-gateway"
      privileged: true
      platform: linux/amd64