name: Create executer-tracker VM disk image and publish task-runner Docker image

on:
  push:
    branches:
      - main
      - dev

    paths:
      - 'common/**'
      - 'executer-tracker/**'

jobs:
  trigger-build-install-image:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow from inductiva/infra-devops to build VM image
        run: |
          if [ "${{ github.ref_name }}" == "main" ];
          then
            PROJECT_ID="inductiva-api"
          else
            PROJECT_ID="inductiva-api-dev"
          fi

          BRANCH=${{ github.ref_name}}

          echo "Triggering workflow to build VM image"
          echo "Branch: $BRANCH"
          echo "Project ID: $PROJECT_ID"

          curl -f -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.INFRA_DEVOPS_WORKFLOW_DISPATCH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/inductiva/infra-devops/actions/workflows/install_image.yaml/dispatches \
            -d '{"ref": "main", "inputs": {"branch": "'$BRANCH'", "gcp-project-id": "'$PROJECT_ID'"}}'


  build-publish-task-runner-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            inductiva/task-runner
          # generate Docker tags based on the branch
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

          labels: |
            org.opencontainers.image.title=task-runner
            org.opencontainers.image.description=Task runner for the Inductiva API
            org.opencontainers.image.url=https://inductiva.ai/
            org.opencontainers.image.source=

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./executer-tracker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
